; This file can be edited to change the style of the application
; Read "Qt Quick Controls 2 Configuration File" for details:
; http://doc.qt.io/qt-5/qtquickcontrols2-configuration.html

[Controls]
;Style=Default
;Style=Material
Style=Universal

[Default]
Foreground = Grey


[Material]
Theme = Light
;Accent=Teal
;Primary=BlueGrey
;Foreground = Grey
;Variant=Dense

[Universal]
Theme = Dark
Accent = "steelblue" ; #4682b4
Background = "#303030"
Foreground = "#FFFAEC" ;"#eeeeee"

;[Universal]
;Theme = Light
;Accent = "#427C91"  ;"#3e65ff"
;Background = "mintcream" ;#f7f7f7"
;Foreground = "#535755"
